name: Dogs-vs-Cats
channels:
- defaults
dependencies:
- certifi=2016.2.28=py35_0
- freetype=2.5.5=2
- h5py=2.7.0=np113py35_0
- hdf5=1.8.17=2
- jbig=2.1=0
- jpeg=9b=0
- libgpuarray=0.6.9=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- mako=1.0.6=py35_0
- markupsafe=1.0=py35_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py35_3
- nose=1.3.7=py35_1
- numpy=1.13.1=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2l=0
- pillow=4.2.1=py35_0
- pip=9.0.1=py35_1
- pygpu=0.6.9=py35_0
- python=3.5.4=0
- readline=6.2=2
- scipy=0.19.1=np113py35_0
- setuptools=36.4.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- theano=0.9.0=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - fancycompleter==0.7
  - keras==2.0.8
  - pdbpp==0.9.1
  - pygments==2.2.0
  - pyyaml==3.12
  - wmctrl==0.3
